/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ConUsuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author David Raigosa
 */
import modelos.Usuario;
import modelos.Trabajador;

import controlador.ConUsuarios;
import controlador.ConTrabajadores;

import java.util.ArrayList;

public class Logup extends javax.swing.JFrame {

    /**
     * Creates new form registrarse
     */
    ConUsuarios controlador;
    ArrayList<Trabajador> arrayTrabajadores;
    boolean isNew;

    public Logup(Usuario modelo) {
        initComponents();
        controlador = new ConUsuarios();
        txtTrabajadores.setEditable(false);
        llenarComboBoxs();
        if (modelo != null) {
            isNew = false;
            txtID.setEditable(false);
            txtID.setText(modelo.getId() + "");
            txtTrabajadores.setText(modelo.getCc_trabajador() + "");
            btnAceptar.setText("Modificar");
            temail.setText(modelo.getEmail() + "");

        } else {
            isNew = true;
            txtID.setEnabled(false);
            btnEliminar.setVisible(false);
            btnAceptar.setText("Crear");

        }
    }

    private void llenarComboBoxs() {
        ConTrabajadores mante = new ConTrabajadores();
        arrayTrabajadores = mante.listar();
        for (Trabajador item : arrayTrabajadores) {
            cbTrabajadores.addItem(item.getCc() + ":" + item.getNombre());
        }

    }

    private Usuario getModelo() {
        if (isNew) {
            return new Usuario(
                    temail.getText(),
                    tContraseña.getText(),
                    Integer.parseInt(txtTrabajadores.getText())
            );

        } else {
            return new Usuario(
                    Integer.parseInt(txtID.getText()),
                    temail.getText(),
                    tContraseña.getText(),
                    Integer.parseInt(txtTrabajadores.getText())
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        temail = new javax.swing.JTextField();
        tContraseña = new javax.swing.JTextField();
        tContraseñar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        txtTrabajadores = new javax.swing.JTextField();
        cbTrabajadores = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Logup"); // NOI18N
        setResizable(false);

        jLabel3.setText("email");

        jLabel4.setText("Contraseña");

        jLabel5.setText("Confirmar contraseña");

        btnAceptar.setText("Crear cuenta");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temailActionPerformed(evt);
            }
        });

        tContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tContraseñaActionPerformed(evt);
            }
        });

        tContraseñar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tContraseñarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        cbTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrabajadoresActionPerformed(evt);
            }
        });

        jLabel6.setText("Trabajador");

        jLabel1.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(temail)
                            .addComponent(tContraseña)
                            .addComponent(tContraseñar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID)
                            .addComponent(txtTrabajadores)
                            .addComponent(cbTrabajadores, 0, 218, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tContraseñar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnEliminar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temailActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        if (isNew) {
            if (!temail.getText().isEmpty() && tContraseña.getText().equals(tContraseñar.getText())) {
                int result = controlador.insert(getModelo());
                if (result == 1) {
                    JOptionPane.showMessageDialog(null, "Usuario Creado");
                    dispose();
                } else if (result == 0) {
                    JOptionPane.showMessageDialog(null, "Usuario ya Existe");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro");
                }
            }

        } else {
            if (!tContraseña.getText().isEmpty() && tContraseña.getText().equals(tContraseñar.getText())) {
                if (controlador.updateConContraseña(getModelo())) {
                    JOptionPane.showMessageDialog(null, "Usuario Modificado");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro");
                };
            } else if (tContraseña.getText().isEmpty()) {
                if (controlador.updateSinContraseña(getModelo())) {
                    JOptionPane.showMessageDialog(null, "Usuario Modificado");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro");
                };
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void tContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tContraseñaActionPerformed

    private void tContraseñarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tContraseñarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tContraseñarActionPerformed

    private void cbTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrabajadoresActionPerformed
        txtTrabajadores.setText(arrayTrabajadores.get(cbTrabajadores.getSelectedIndex()).getCc() + "");
    }//GEN-LAST:event_cbTrabajadoresActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        controlador.delete(getModelo());
        dispose();
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbTrabajadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tContraseña;
    private javax.swing.JTextField tContraseñar;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTrabajadores;
    // End of variables declaration//GEN-END:variables
}
